name = "y-tu-que-compras"
account_id = "173bf7921f79923475ce95a48b845583"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "y-tu-que-compras"
database_id = "0a880a29-1c6d-4e24-bed8-9b96cb25680f"


